#!/bin/python3

import sys

n = int(input().strip())
a = list(map(int, input().strip().split(' ')))
# Write Your Code Here
swap=0
for i in range(0,n):
    for j in range(0,n-i-1):
        if a[j]>a[j+1]:
            t=a[j]
            a[j]=a[j+1]
            a[j+1]=t
            swap+=1
    if swap==0:
        break
print("Array is sorted in",swap,"swaps.")
print("First Element:",a[0])
print("Last Element:",a[n-1])
